# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class 2nb < Formula
  desc "AI-native markdown knowledge base with semantic search, RAG, and MCP server"
  homepage "https://github.com/apresai/2ndbrain"
  version "0.1.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/apresai/2ndbrain/releases/download/v0.1.1/2nb_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "8d08de57e861bead58453b2097d4be56ec3db7597f242e422dfdec6f963e29cb"

    define_method(:install) do
      bin.install "2nb"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/apresai/2ndbrain/releases/download/v0.1.1/2nb_0.1.1_Darwin_arm64.tar.gz"
    sha256 "28c207b177982e23d7200f4b577a3a47cbec249d8beb5882ed04c486fdb3fd1c"

    define_method(:install) do
      bin.install "2nb"
    end
  end

  def caveats
    <<~EOS
      To get started:

        # Initialize a new vault
        2nb init --path ~/my-vault

        # Or open an existing Obsidian vault
        2nb import-obsidian ~/my-obsidian-vault

        # Set up local AI with Ollama
        2nb ai setup

      For full documentation:
      https://github.com/apresai/2ndbrain
    EOS
  end

  test do
    system "#{bin}/2nb", "--help"
  end
end
