# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gimage < Formula
  desc "AI-powered image generation and processing CLI with AWS Lambda deployment manager"
  homepage "https://github.com/apresai/gimage"
  version "1.2.147"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/apresai/gimage/releases/download/v1.2.147/gimage_1.2.147_Darwin_x86_64.tar.gz"
      sha256 "e9fe1ce187112646de5e61570c78acd4788d410a928dc85af280ae3e580fc759"

      define_method(:install) do
        bin.install "gimage"
        bin.install "gimage-deploy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/apresai/gimage/releases/download/v1.2.147/gimage_1.2.147_Darwin_arm64.tar.gz"
      sha256 "f322cb076f4020aa6d857c036a36981ebc6285c216f97edf790b23b370687d83"

      define_method(:install) do
        bin.install "gimage"
        bin.install "gimage-deploy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/apresai/gimage/releases/download/v1.2.147/gimage_1.2.147_Linux_x86_64.tar.gz"
      sha256 "d269242da29b008d93a147d494429dfac7afa61a97bf3274471bf22ce06591fa"
      define_method(:install) do
        bin.install "gimage"
        bin.install "gimage-deploy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/apresai/gimage/releases/download/v1.2.147/gimage_1.2.147_Linux_arm64.tar.gz"
      sha256 "af696063da9caa75901d8be5685d10501010af3ef8a4aac9232cfad315120eba"
      define_method(:install) do
        bin.install "gimage"
        bin.install "gimage-deploy"
      end
    end
  end

  def caveats
    <<~EOS
      Two tools have been installed:

      1. gimage - Image generation and processing CLI
      2. gimage-deploy - AWS Lambda deployment manager

      To get started with gimage:

      1. Set up API credentials:
         gimage auth gemini

      2. Get your free Gemini API key:
         https://aistudio.google.com/app/apikey

      3. Generate your first image:
         gimage generate "a sunset over mountains"

      To deploy gimage as AWS Lambda:

         gimage-deploy deploy
         gimage-deploy tui  # Interactive UI

      For full documentation:
      https://github.com/apresai/gimage
    EOS
  end

  test do
    system "#{bin}/gimage", "--version"
    system "#{bin}/gimage-deploy", "--version"
  end
end
