# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gimage < Formula
  desc "AI-powered image generation and processing CLI with AWS Lambda deployment manager"
  homepage "https://github.com/apresai/gimage"
  version "1.2.131"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/apresai/gimage/releases/download/v1.2.131/gimage_1.2.131_Darwin_x86_64.tar.gz"
      sha256 "588e6d3ef5485d7d15d5adbd183276fc9b2c2065d469c430b52036fce58b949f"

      define_method(:install) do
        bin.install "gimage"
        bin.install "gimage-deploy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/apresai/gimage/releases/download/v1.2.131/gimage_1.2.131_Darwin_arm64.tar.gz"
      sha256 "a2c21663bc0694ef16a84de86e90729bc6a20e7042bd9f6538b7bce0e69afd85"

      define_method(:install) do
        bin.install "gimage"
        bin.install "gimage-deploy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/apresai/gimage/releases/download/v1.2.131/gimage_1.2.131_Linux_x86_64.tar.gz"
      sha256 "add48f90e0501ab26095e2966c4f15f5fff482e5f36c339e4d52b1f8598a1785"
      define_method(:install) do
        bin.install "gimage"
        bin.install "gimage-deploy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/apresai/gimage/releases/download/v1.2.131/gimage_1.2.131_Linux_arm64.tar.gz"
      sha256 "5ca2f920021938d35df3badbffaaeb5ae6d54233140cee862f4db3370c2375ed"
      define_method(:install) do
        bin.install "gimage"
        bin.install "gimage-deploy"
      end
    end
  end

  def caveats
    <<~EOS
      Two tools have been installed:

      1. gimage - Image generation and processing CLI
      2. gimage-deploy - AWS Lambda deployment manager

      To get started with gimage:

      1. Set up API credentials:
         gimage auth gemini

      2. Get your free Gemini API key:
         https://aistudio.google.com/app/apikey

      3. Generate your first image:
         gimage generate "a sunset over mountains"

      To deploy gimage as AWS Lambda:

         gimage-deploy deploy
         gimage-deploy tui  # Interactive UI

      For full documentation:
      https://github.com/apresai/gimage
    EOS
  end

  test do
    system "#{bin}/gimage", "--version"
    system "#{bin}/gimage-deploy", "--version"
  end
end
