# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gimage < Formula
  desc "AI-powered image generation and processing CLI with AWS Lambda deployment manager"
  homepage "https://github.com/apresai/gimage"
  version "1.2.161"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/apresai/gimage/releases/download/v1.2.161/gimage_1.2.161_Darwin_x86_64.tar.gz"
      sha256 "aecf140aa83c720f122cee2de3d464abde4031830eab52a0f0d0c258525b3b9a"

      define_method(:install) do
        bin.install "gimage"
        bin.install "gimage-deploy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/apresai/gimage/releases/download/v1.2.161/gimage_1.2.161_Darwin_arm64.tar.gz"
      sha256 "7c033c24d9874f3f1be837cc8f4a89af83144a8fc38e5ce727df1e007319e641"

      define_method(:install) do
        bin.install "gimage"
        bin.install "gimage-deploy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/apresai/gimage/releases/download/v1.2.161/gimage_1.2.161_Linux_x86_64.tar.gz"
      sha256 "3451b22bc95a0dca059c484bcf3f03f76db3b9b7223ef7b4e2d736031fd2cc4d"
      define_method(:install) do
        bin.install "gimage"
        bin.install "gimage-deploy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/apresai/gimage/releases/download/v1.2.161/gimage_1.2.161_Linux_arm64.tar.gz"
      sha256 "8d032fb2a33dde6cf1c3dccd0cc752c46f8bcf7bda68b702de4dee09da99434f"
      define_method(:install) do
        bin.install "gimage"
        bin.install "gimage-deploy"
      end
    end
  end

  def caveats
    <<~EOS
      Two tools have been installed:

      1. gimage - Image generation and processing CLI
      2. gimage-deploy - AWS Lambda deployment manager

      To get started with gimage:

      1. Set up API credentials:
         gimage auth gemini

      2. Get your free Gemini API key:
         https://aistudio.google.com/app/apikey

      3. Generate your first image:
         gimage generate "a sunset over mountains"

      To deploy gimage as AWS Lambda:

         gimage-deploy deploy
         gimage-deploy tui  # Interactive UI

      For full documentation:
      https://github.com/apresai/gimage
    EOS
  end

  test do
    system "#{bin}/gimage", "--version"
    system "#{bin}/gimage-deploy", "--version"
  end
end
