# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Twonb < Formula
  desc "AI-native markdown knowledge base with semantic search, RAG, and MCP server"
  homepage "https://github.com/apresai/2ndbrain"
  version "0.9.8"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/apresai/2ndbrain/releases/download/v0.9.8/2nb_0.9.8_Darwin_x86_64.tar.gz"
    sha256 "5a1018296e42b498aed86f4829b026fc0a21b8efb9b4f8e2f9f18faeaf5aa465"

    define_method(:install) do
      bin.install "2nb"

      # Generate and install shell completions so tab-complete
      # and dynamic value suggestions work out of the box for
      # Homebrew users.
      generate_completions_from_executable(bin/"2nb", "completion")
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/apresai/2ndbrain/releases/download/v0.9.8/2nb_0.9.8_Darwin_arm64.tar.gz"
    sha256 "17beb94251bad5451afe37493805c38c39f31d392dd0b7db8b9084364b3155cf"

    define_method(:install) do
      bin.install "2nb"

      # Generate and install shell completions so tab-complete
      # and dynamic value suggestions work out of the box for
      # Homebrew users.
      generate_completions_from_executable(bin/"2nb", "completion")
    end
  end

  def caveats
    <<~EOS
      To get started:

        # Initialize a new vault
        2nb vault create ~/my-vault

        # Or open an existing Obsidian vault
        2nb import-obsidian ~/my-obsidian-vault

        # Set up local AI with Ollama
        2nb ai setup

      Shell completions are installed automatically. Restart your shell
      (or `source ~/.zshrc`) to pick them up.

      For full documentation:
      https://github.com/apresai/2ndbrain
    EOS
  end

  test do
    system "#{bin}/2nb", "--help"
  end
end
