# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Twonb < Formula
  desc "AI-native markdown knowledge base with semantic search, RAG, and MCP server"
  homepage "https://github.com/apresai/2ndbrain"
  version "0.4.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/apresai/2ndbrain/releases/download/v0.4.1/2nb_0.4.1_Darwin_x86_64.tar.gz"
    sha256 "007dc19ef549978e4f7f266728aa4a95374174f8b638a30d7de982190557dd1a"

    define_method(:install) do
      bin.install "2nb"

      # Generate and install shell completions so tab-complete
      # and dynamic value suggestions work out of the box for
      # Homebrew users.
      generate_completions_from_executable(bin/"2nb", "completion")
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/apresai/2ndbrain/releases/download/v0.4.1/2nb_0.4.1_Darwin_arm64.tar.gz"
    sha256 "1e3c098cf2bda7156d2f21438d32af7a024194792bba4e92445010f4c9a3883a"

    define_method(:install) do
      bin.install "2nb"

      # Generate and install shell completions so tab-complete
      # and dynamic value suggestions work out of the box for
      # Homebrew users.
      generate_completions_from_executable(bin/"2nb", "completion")
    end
  end

  def caveats
    <<~EOS
      To get started:

        # Initialize a new vault
        2nb vault create ~/my-vault

        # Or open an existing Obsidian vault
        2nb import-obsidian ~/my-obsidian-vault

        # Set up local AI with Ollama
        2nb ai setup

      Shell completions are installed automatically. Restart your shell
      (or `source ~/.zshrc`) to pick them up.

      For full documentation:
      https://github.com/apresai/2ndbrain
    EOS
  end

  test do
    system "#{bin}/2nb", "--help"
  end
end
