# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Twonb < Formula
  desc "AI-native markdown knowledge base with semantic search, RAG, and MCP server"
  homepage "https://github.com/apresai/2ndbrain"
  version "0.4.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/apresai/2ndbrain/releases/download/v0.4.0/2nb_0.4.0_Darwin_x86_64.tar.gz"
    sha256 "318ad1dd320ca35b6b2dbaa34b43ac4086d81b5bf8d70f4da15824fa154c2417"

    define_method(:install) do
      bin.install "2nb"

      # Generate and install shell completions so tab-complete
      # and dynamic value suggestions work out of the box for
      # Homebrew users.
      generate_completions_from_executable(bin/"2nb", "completion")
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/apresai/2ndbrain/releases/download/v0.4.0/2nb_0.4.0_Darwin_arm64.tar.gz"
    sha256 "866ef9569fa22b48e36353004bf2c5c20d30a46a2377900d3b3ed34694a8d729"

    define_method(:install) do
      bin.install "2nb"

      # Generate and install shell completions so tab-complete
      # and dynamic value suggestions work out of the box for
      # Homebrew users.
      generate_completions_from_executable(bin/"2nb", "completion")
    end
  end

  def caveats
    <<~EOS
      To get started:

        # Initialize a new vault
        2nb vault create ~/my-vault

        # Or open an existing Obsidian vault
        2nb import-obsidian ~/my-obsidian-vault

        # Set up local AI with Ollama
        2nb ai setup

      Shell completions are installed automatically. Restart your shell
      (or `source ~/.zshrc`) to pick them up.

      For full documentation:
      https://github.com/apresai/2ndbrain
    EOS
  end

  test do
    system "#{bin}/2nb", "--help"
  end
end
